# name: Bench A11yWatch
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# env:
#   AI_DISABLED: true

# jobs:
#   run-container:
#     name: Bench Website Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: A11yWatch website scan
#         uses: ./
#         with:
#           WEBSITE_URL: https://dev.events.beeem.com/
#           FAIL_TOTAL_COUNT: 0
#           EXTERNAL: false
#           SITE_WIDE: true
#           SUBDOMAINS: false
#           TLD: false
#           LIST: true
#           UPGRADE: false