name: Bench Axe

on:
  pull_request:
    branches-ignore:
      - main, master
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install -g @axe-core/cli
      - name: Run axe
        run: |
          axe https://dev.events.beeem.com/